INSERT INTO ejercicios (focus, movement, level, type, exercises) VALUES 
('Push', 'Horizontal', 'Elite', 'Time', 'Planche'),
('Push', 'Horizontal', 'Elite', 'Time', 'Straddle planche'),
('Push', 'Horizontal', 'Advaced', 'Time', 'Tuck advance planche'),
('Push', 'Horizontal', 'Intermediate', 'Time', 'Tuck planche'),
('Push', 'Horizontal', 'Beginner', 'Time', 'Planche lean'),
('Push', 'Vertical', 'Advaced', 'Reps', 'Handstand push ups 90°'),
('Push', 'Vertical', 'Advaced', 'Reps', 'Handstand push ups'),
('Balance', 'Vertical', 'Intermediate', 'Time', 'Handstand '),
('Push', 'Vertical', 'Intermediate', 'Time', 'Assisted Handstand push ups'),
('Balance', 'Vertical', 'Beginner', 'Time', 'Wall Handstand (chest)'),
('Balance', 'Vertical', 'Beginner', 'Time', 'Wall Handstand (back)'),
('Core', 'Vertical', 'Newbie', 'Time', 'Wall climbers'),
('Push', 'Diagonal', 'Newbie', 'Reps', 'Pike compression'),
('Push', 'Diagonal', 'Intermediate', 'Time', 'Pike push ups'),
('Balance', 'Horizontal', 'Beginner', 'Reps', 'Elbow planche'),
('Push', 'Horizontal', 'Intermediate', 'Time', 'Hollow push ups'),
('Push', 'Horizontal', 'Intermediate', 'Reps', 'One arm push ups'),
('Push', 'Horizontal', 'Intermediate', 'Reps', 'Negative One arm push ups'),
('Push', 'Horizontal', 'Intermediate', 'Reps', 'Assisted One arm push ups'),
('Push', 'Horizontal', 'Intermediate', 'Reps', 'Archer push ups'),
('Push', 'Horizontal', 'Intermediate', 'Reps', 'Tiger push ups'),
('Push', 'Horizontal', 'Intermediate', 'Reps', 'Diamond push ups'),
('Push', 'Horizontal', 'Beginner', 'Reps', 'Wide push ups'),
('Push', 'Horizontal', 'Beginner', 'Reps', 'Push ups'),
('Push', 'Horizontal', 'Newbie', 'Reps', 'Scapular Push ups'),
('Push', 'Horizontal', 'Newbie', 'Reps', 'Negative Push ups'),
('Core', 'Horizontal', 'Newbie', 'Time', 'Plank'),
('Pull', 'Horizontal', 'Advaced', 'Time', 'Front lever'),
('Pull', 'Horizontal', 'Advaced', 'Reps', 'Front lever raises'),
('Pull', 'Horizontal', 'Advaced', 'Time', 'Straddle front lever'),
('Pull', 'Horizontal', 'Advaced', 'Reps', 'Straddle front lever raises'),
('Pull', 'Horizontal', 'Advaced', 'Time', 'Half front lever'),
('Pull', 'Horizontal', 'Advaced', 'Reps', 'Half front lever raises'),
('Pull', 'Horizontal', 'Advaced', 'Time', 'One leg front lever'),
('Pull', 'Horizontal', 'Advaced', 'Reps', 'One leg front lever raises'),
('Pull', 'Horizontal', 'Intermediate', 'Time', 'Tuck advance front lever'),
('Pull', 'Horizontal', 'Intermediate', 'Reps', 'Tuck advance front lever raises'),
('Pull', 'Horizontal', 'Intermediate', 'Reps', 'Inverted L row'),
('Pull', 'Horizontal', 'Intermediate', 'Time', 'Tuck front lever'),
('Pull', 'Horizontal', 'Intermediate', 'Reps', 'Tuck front lever raises'),
('Pull', 'Horizontal', 'Intermediate', 'Reps', 'Inverted tuck row'),
('Core', 'Vertical', 'Beginner', 'Reps', 'Toes to bar'),
('Core', 'Vertical', 'Intermediate', 'Reps', 'Hanging leg raises'),
('Core', 'Vertical', 'Beginner', 'Reps', 'Hanging knee raises'),
('Core', 'Diagonal', 'Intermediate', 'Reps', 'Dragonflags'),
('Core', 'Diagonal', 'Intermediate', 'Time', 'Isometrics dragonflags'),
('Core', 'Diagonal', 'Intermediate', 'Reps', 'Straddle dragonflags'),
('Core', 'Diagonal', 'Intermediate', 'Reps', 'One leg dragonflags'),
('Core', 'Diagonal', 'Intermediate', 'Reps', 'Dragonflags extensions'),
('Core', 'Horizontal', 'Beginner', 'Reps', 'Lying leg raises'),
('Core', 'Horizontal', 'Newbie', 'Reps', 'Lying knee raises'),
('Core', 'Horizontal', 'Newbie', 'Time', 'Hollow hold'),
('Core', 'Horizontal', 'Newbie', 'Reps', 'Abs crunches'),
('Pull', 'Horizontal', 'Intermediate', 'Reps', 'Declined inverted row'),
('Pull', 'Horizontal', 'Beginner', 'Reps', 'Inverted row'),
('Pull', 'Vertical', 'Intermediate', 'Reps', 'Muscle up'),
('Pull', 'Vertical', 'Intermediate', 'Reps', 'Hollow pull ups'),
('Pull', 'Vertical', 'Intermediate', 'Reps', 'Chest pull ups'),
('Pull', 'Vertical', 'Beginner', 'Reps', 'Jumping Muscle ups'),
('Core', 'Vertical', 'Intermediate', 'Reps', 'Negative Muscle ups'),
('Core', 'Vertical', 'Beginner', 'Time', 'L-sit Dead hang'),
('Core', 'Vertical', 'Newbie', 'Time', 'Dead hang'),
('Pull', 'Vertical', 'Intermediate', 'Reps', 'Typewritter pull ups'),
('Pull', 'Vertical', 'Intermediate', 'Reps', 'Archer pull ups'),
('Pull', 'Vertical', 'Intermediate', 'Reps', 'Asymmetric pull ups'),
('Pull', 'Vertical', 'Beginner', 'Reps', 'Wide pull ups '),
('Pull', 'Vertical', 'Beginner', 'Reps', 'Command pull ups'),
('Pull', 'Vertical', 'Beginner', 'Reps', 'Close pull ups'),
('Pull', 'Vertical', 'Beginner', 'Reps', 'Pull ups'),
('Pull', 'Vertical', 'Beginner', 'Reps', 'Neutral grip pull ups'),
('Pull', 'Vertical', 'Beginner', 'Reps', 'Close chin ups'),
('Pull', 'Vertical', 'Newbie', 'Reps', 'Chin ups'),
('Pull', 'Vertical', 'Newbie', 'Reps', 'Negative pull ups'),
('Pull', 'Vertical', 'Newbie', 'Time', 'Excentric pull ups'),
('Pull', 'Vertical', 'Newbie', 'Reps', 'Scapular pull ups'),
('Push', 'Vertical', 'Intermediate', 'Reps', 'Bar dips'),
('Push', 'Vertical', 'Beginner', 'Reps', 'Chest dips'),
('Push', 'Vertical', 'Beginner', 'Reps', 'Tricep dips'),
('Push', 'Vertical', 'Newbie', 'Reps', 'Chair dips'),
('Leg', 'Vertical', 'Intermediate', 'Reps', 'Pistol squats'),
('Leg', 'Vertical', 'Intermediate', 'Reps', 'Bulgarian squats'),
('Leg', 'Vertical', 'Beginner', 'Reps', 'Lunges'),
('Leg', 'Vertical', 'Beginner', 'Reps', 'Jump squats'),
('Leg', 'Vertical', 'Beginner', 'Reps', 'Squats'),
('Leg', 'Vertical', 'Newbie', 'Time', 'Wall squats'),
('Leg', 'Diagonal', 'Intermediate', 'Reps', 'Sissy squats'),
('Leg', 'Diagonal', 'Intermediate', 'Reps', 'Reverse extensions'),
('Leg', 'Vertical', 'Beginner', 'Reps', 'Deadlift'),
('Leg', 'Horizontal', 'Beginner', 'Reps', 'Hip trust'),
('Leg', 'Horizontal', 'Newbie', 'Reps', 'Glute bridge');